install:
- git clone https://github.com/dperezcabrera/jpoker.git
language: java
jdk:
- oraclejdk8
sudo: false
script: mvn clean verify
cache:
  directories:
  - "$HOME/.m2"
after_success:
- mvn jacoco:report coveralls:jacoco
- mvn coveralls:report

notifications:
  email:
  - dperezcabrera@gmail.com
