install:
- git clone https://github.com/dperezcabrera/jpoker.git
language: java
jdk:
- oraclejdk8
sudo: false
script: mvn clean verify
cache:
  directories:
  - "$HOME/.m2"
after_success:
- mvn clean test jacoco:report coveralls:jacoco -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID

notifications:
  email:
  - dperezcabrera@gmail.com
env:
  global:
    - GIT_DEPENDENCIES=""
    - GH_USERNAME=dperezcabrera
    - GH_REPO=dperezcabrera/jpoker
