install:
- git clone https://github.com/dperezcabrera/jpoker.git
language: java
jdk:
- oraclejdk8
mvn install -DskipTests=false
cache:
  directories:
  - "$HOME/.m2"
after_success:
- mvn jacoco:report coveralls:jacoco
notifications:
  email:
  - dperezcabrera@gmail.com
